### ISSUE TITLE
Import dependency

### ISSUE THREAD

**Issue by aligit93** [zourtney/angular-checklist#1]
How do I import the dependency when I used the install via NPM?
 (Path: ../node_modules/angular-checklist)
`import {ChecklistModule} from 'angular-checklist'` does not work.

I am using SystemJS as my module loader:

```javascript
System.config({
        paths: {
            'npm:': 'node_modules/'
        },
        map: {
            /...
            'angular-checklist': 'npm:angular-checklist', //...?
            .../
        }
});
```

**Comment by zourtney** [comment]
Thanks for reporting this -- there's likely something wrong with how I exposed the compiled JS. I'll try to look into it tomorrow.

Until then, you'll need to add a rule* to allow importing `*.ts` from `node_modules/angular-checklist/src`. I'm now realizing all my usages lazily use this approach.

For example, my _webpack.config.js_:

```javascript
module: {
  rules: [
    {
      test: /\.ts$/,
      include: [
        path.join(shared.PROJECT_ROOT, 'node_modules', 'angular-checklist', 'src'),
      ],
    },
    ...
} 
```

----

*I have almost no experience with SystemJS and I'm not sure where this fits in your build system. TSC? Babel config?

**Comment by zourtney** [comment]
Try version `1.2.1`.

The compiled `*.js` files are now included and `*.ts` files are excluded. My webpack builds now work without the special rule (above). Let me know whether or not it works with SystemJS.

----

References:

- http://blog.mgechev.com/2017/01/21/distributing-an-angular-library-aot-ngc-types/
- https://medium.com/@OCombe/how-to-publish-a-library-for-angular-2-on-npm-5f48cdabf435
- https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by zourtney** [comment]
Ok, I pushed out another update: `1.2.2`. This build uses CommonJS module syntax instead of the ES6+ style (`require`s instead of `import`s).

I'm really unfamiliar with SystemJS, but hobbled [this plunker](https://plnkr.co/edit/1MnbW4eg4NRFdkhSptRQ?p=preview) together. I was only able to get it working after: 

1. switching to CommonJS modules
2. mapping directly to the _dist/index.js_ file

```js
map: {
  'angular-checklist': 'https://npmcdn.com/angular-checklist@1.2.2/dist/index.js'
}
```

The latest build works fine with Webpack and my SystemJS plunker. But there's probably a better fix, so feel free to reopen if you have any issues or suggestions.

**Comment by aligit93** [comment]
Now it works fine, thank you!

**Comment by adsnasa** [comment]
`import {ChecklistModule} from 'angular-checklist' does not work`
if i use below link provided by you, it works.
`map: {
  'angular-checklist': 'https://npmcdn.com/angular-checklist@1.2.2/dist/index.js'
}`

but if download your package and give the local path it does not work
`map: {
  'angular-checklist': 'node_modules/angular-checklist/dist/index.js'
}`

it  shows below error
Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/node_modules/angular-checklist/dist/directives/checklist.directive

**Comment by zourtney** [comment]
@adsnasa, I'm not sure, since I'm not too familiar with SystemJS. Are you sure it's downloading the latest version (`1.2.3`)? The first few releases **were** indeed missing the _dist_ directory.

I verified that the latest release works correctly using Webpack. If you can set up a full working SystemJS example in Plunkr (or similar), I will try to debug it.

**Comment by adsnasa** [comment]
Yes i am using version (1.2.3) and **checklist.directive.js** is also there inside angular-checklist\dist\directives.
But it shows Error: (SystemJS) XHR error (404 Not Found)  if i use local reference.

**Comment by adsnasa** [comment]
I used ng2-pagination plugin which was giving the same error.
But I resolved the error by including 
<script src="node_modules/ng2-pagination/dist/ng2-pagination-bundle.js"></script>
in my index.html.
Is there anything similar which will resolve the **angular-checklist** 404 Not Found error

**Comment by zourtney** [comment]
There's something about the internal `require` call that SystemJS doesn't like. I tried setting `defaultExtension: 'js'`, but it seemed to have no effect:

```javascript
var packages = {
  /* ... */
  'angular-checklist': { defaultExtension: 'js' }   // doesn't work
};
```

What _did_ work was to set `defaultJSExtensions` -- what looks to be globally:

```javascript
var map = {
  /* ... */
  'angular-checklist': 'node_modules/angular-checklist/dist/index.js',
};

var packages = {
  /* ... */
  '.': { defaultJSExtensions: 'js' }
};
```

This feels like a hacky solution, bound to break something else in any sizable project. Let me know if you come up with any better solutions.

----

References:
- https://stackoverflow.com/a/41308796/311207
- https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md

**Comment by adsnasa** [comment]
I tried your solution.
But not working for me.
