### ISSUE TITLE
Angular 9 compatibility issue with angular-checklist when IVY enabled

### ISSUE THREAD

**Issue by VishnuVardhanReddyRc** [zourtney/angular-checklist#12]
This is the error i am  getting after migrating to angular 9  and tries to build application

![image](https://user-images.githubusercontent.com/52275154/76570675-e15ff880-64db-11ea-8aa9-269b633f0a69.png)

**Comment by myersBR** [comment]
Am I having the same error? Any position? Will an update be released?

**Comment by zourtney** [comment]
Sorry for the delay -- yes, I will update this component to be compatible with Angular 9.
I'll try to find time today.

**Comment by zourtney** [comment]
I've rebuilt the lib and published to NPM as `1.4.1-dev`. Free free to try it out; I appreciate any feedback.

I'll continue to test it, as time allows. I will publish an non-dev version in a few days.

**Comment by myersBR** [comment]
> I've rebuilt the lib and published to NPM as `1.4.1-dev`. Free free to try it out; I appreciate any feedback.
> 
> I'll continue to test it, as time allows. I will publish an non-dev version in a few days.

Thanks, everything seems to be working again. I will continue testing, awaiting the final version.

**Comment by zourtney** [comment]
I just published these changes to non-dev build `1.4.1`, available via NPM.
Feel free to comment / reopen if you have any issues.
