### ISSUE TITLE
Binding with and setted array does not work

### ISSUE THREAD

**Issue by jakoujan** [zourtney/angular-checklist#4]
Hi, im posting this issue because the library does not work with and setted arraythis is my html code

```
<div class="form-check" *ngFor="let role of roles">
 <label class="form-check-label">
   <input type="checkbox" name="roles" [(checklist)]="user.roles" [checklistValue]="role" class="form-check-input" > {{role.description}}
 </label>
</div>
```

where user.roles have 2 roles inserted and this roles are the same object in the list of ngFor every role are in the two arrays.

```
roles = [{role: "ROLE1", desc: "DESC ROLE 1"}, {role: "ROLE2", desc: "DESC ROLE 2"}]
user = {
   name:"User",
   roles : [{role: "ROLE1", desc: "DESC ROLE 1"}, {role: "ROLE2", desc: "DESC ROLE 2"}]
}

```
and im having 2 checkboxes unselected when i expecting 2 checkboxes should be selected.

question am i doing something wrong or it is a issue in the library?

thanks in advance

**Comment by zourtney** [comment]
Hey there!

I'm think this is failing because the library does not perform deep object comparisons when setting the selected value (see #2). Instead it uses a simple `indexOf` lookup. To work, `user.roles[x]` has to be the same _instance_ as that of `roles[x]`.

**Lame solution**

Set `user.roles[x]` to the existing `roles` array instances:

```ts
user = {
  name: "User",
  roles: [ roles[0], roles[1] ],
};
```

This doesn't make much sense in the context of API-driven data.

**Better solution:**

1. Define `user.roles` as an array of `role.role` strings.

```ts
user = {
  name: "User",
  roles: [ 'ROLE1', 'ROLE2' ],
};
```

2. Then set `[checklistValue]="role.role"`:

```html
<div class="form-check" *ngFor="let role of roles">
  <label class="form-check-label">
    <input type="checkbox"
           name="roles"
           [(checklist)]="user.roles"
           [checklistValue]="role.role"
           class="form-check-input" />
    {{role.description}}
 </label>
</div>
```

Hopefully that made sense. If not, let me know!

**Comment by jakoujan** [comment]
hi, zourtney thanks for your reply,

after look for a better(elegant) solution, and can't find another one, i wrote another directive inspired in your code this directive could be improved but the aproach is to find the objects in selected arrays but is not suitable for other objects without modification.

```
import { Directive, Input, Output, EventEmitter, OnChanges, HostListener } from '@angular/core';
import { Role } from '../entity/role';

@Directive({
  // tslint:disable-next-line:directive-selector
  selector: '[rolecl]',
  // tslint:disable-next-line:use-host-property-decorator
  host: {
    '[checked]': 'isChecked'
  }
})
export class RoleCheckListDirective implements OnChanges {

  @Input() rolecl: Role[];
  @Input() role: Role;
  @Output() checklistChange = new EventEmitter<Role[]>();

  isChecked = false;

  constructor() { }

  ngOnChanges() {
    this.rolecl.forEach(role => {
      if (role.role === this.role.role) {
        this.isChecked = true;
      }
    });
  }

  @HostListener('change', ['$event.target']) triggerOnChange(target) {
    if (target.checked) {
        this.rolecl.push(this.role);
    } else {
      let i = 0;
      this.rolecl.forEach(role => {
        if (this.role.role === role.role) {
          this.rolecl.splice(i, 1);
        }
        i++;
      });
    }
    this.checklistChange.emit(this.rolecl);
  }
}
```
as you can see this directive only works with Role objects but it can be modified to suit with an other type of objects (i'm newbie in angular 2+) i came from angular 1 maybe with an object comparsion function (maybe with lodash comparsion function _.isEqual()) could be performed with better common object compatibility

well thank you so much for your help.
