### ISSUE TITLE
Select\Unselect all

### ISSUE THREAD

**Issue by martinobordin** [zourtney/angular-checklist#7]
Hi, could you add Select\Unselect all functionalities?

**Comment by zourtney** [comment]
For now, I'm going to say this falls outside the scope of this project. And that the best way to do this is to simply handle it from within the parent component. The directive watches for list changes, so simply set it to "full" or "empty" accordingly.

Something like:

```html
<button (click)="selectAll()">All</button>
<button (click)="selectNone()">None</button>

<label *ngFor="let opt of options">
  <input type="checkbox" [(checklist)]="list" [checklistValue]="opt" />
</label>
```

```ts
// In the component
@Component({ ... })
export class MyComponent {
  list: number[];
  options = [1, 2, 3];

  selectAll() {
    this.list = [...options];
  }

  selectNone() {
    this.list = [];
  }
}
```

Feel free to reopen if you have further questions... or rebuttals 😄
