### ISSUE TITLE
pick object

### ISSUE THREAD

**Issue by mohammed-a-wadod** [zourtney/angular-checklist#9]
how can i pick object using the new version like the following example 

```
<label ng-repeat="role in roles">
  <input type="checkbox" data-checklist-model="user.roles" data-checklist-value="role"> {{role.text}}
</label>
```
I am using angular 5

**Comment by mohammed-a-wadod** [comment]
I found solution after editing in this file: **checklist.directive.js**  and edit this method ### **ChecklistDirective.prototype.ngOnChanges** as the following : 
```
ChecklistDirective.prototype.ngOnChanges = function () {
        var checklist = this.checklist || [];
        // this.isChecked = checklist.indexOf(this.checklistValue) >= 0;
        var checklistValue = this.checklistValue;
        this.isChecked = checklist.some(element => {return JSON.stringify(element) === JSON.stringify(checklistValue) });
    };
```
is this valid code or not, please response, and how can i contribute in this lib?
thanks for your time

**Comment by zourtney** [comment]
Sorry for the delay. Can you give me a more concrete example of the data you're working with? I think the answer is to use the `checklistValue` binding, but maybe I'm missing something.

Like:

```html
<label *ngFor="let opt of options">
  <input type="checkbox" [(checklist)]="selectedOptions" [checklistValue]="opt.value" />
  {{opt.text}}
</label>
```

Where the data is something like:

```js
let options = [
  { text: 'One', value: 1 },
  { text: 'Two', value: 2 },
];

let selectedOptions = [ 1 ];
```

Are you looking for `value` to be a complex object?

**Comment by mohammed-a-wadod** [comment]
Ok, according to your code example i want to add opt object to my selectedOption array, not opt.value 
in my code opt is more complex json object so i need it to send it back to my JAVA rest application

**Comment by rroex** [comment]
I am looking for a similar solution. Maybe we have to add another directive which can be bound to a compare function. 

An example:

`<label *ngFor="let opt of options">
  <input type="checkbox" [(checklist)]="selectedOptions" [checklistValue]="opt" [checklistValueCompare]="compareById" />
  {{opt.text}}
</label>`

Where the compare functions is something like:

`public compareById(itemOne, itemTwo) {
    return itemOne && itemTwo && itemOne.id === itemTwo.id;
  }`

Where the data is something like:

`let options = [
  { text: 'One', value: 1 },
  { text: 'Two', value: 2 },
];

let selectedOptions = [ {text: 'One', value: 1} ];`

**Comment by zourtney** [comment]
Cleaning up and closing this issue out. If there are still problems, please open a new issue.
